#' reallocationPlot
#' @description Visualization of predictions from CoDA model
#'
#' @param data Data frame with the data
#' @param comp String with the name of the composition variables in dataf
#' @param comp_fup String with the name of the follow-up composition variables in dataf (optional)
#' @param comp.names Names of the composition variables to appear in the plot (it will use \code{comp} if not provided)
#' @param outcome String with the name of the outcome in dataf
#' @param covs String with the name of the covariates
#' @param comparisons Two choices ("one-v-one" or "prop-realloc")
#' @param increase What variable in the composition should increase in the visualization (replacement)
#' @param decrease What variable/s in the composition should decrease in the visualization (replaced)
#' @param xlab X axis label
#' @param ylab Y axis label
#' @param xlim Limits of the X axis (time reallocation limits)
#' @param ylim Limits for the Y axis (autogenerated if not provided)
#' @param xaxis.by X axis ticks at every \code{xaxis.by} minutes
#' @param ribbon Logical. Whether to plot confidence intervals of the predictions
#' @param font Font to use (default = "Times New Roman")
#'
#' @details If follow-up composition is provided, it will run prospective and change models/visualizations
#' @return reallocation plot with predictions
#' @export
#'
#' @import ggplot2
#'
reallocationPlot = function(data = c(), comp = c(),
                            comp_fup = NULL,
                            comp.names = c(),
                            outcome = c(), covs = c(),
                            comparisons=c("one-v-one","prop-realloc")[1],
                            # balance = NULL,
                            increase = c(), decrease = c(),
                            xlab = c(), ylab = c(),
                            xlim = c(), ylim = c(),
                            xaxis.by = 5,
                            ribbon = TRUE,
                            font = "Times New Roman"){
  require(ggplot2)

  # define dataset
  df = data[, c(comp, outcome, covs)]
  if(!is.null(comp_fup)) df = data[,c(comp, comp_fup, outcome, covs)]

  if(length(comp.names) == length(comp)) {
    colnames(df)[1:length(comp)] = comp.names
    comp = comp.names
  } else {warning("composition names is of different length than the number of
                  elements in the composition. comp.names argument is not used.")}



  # get changes
  plot_data = get_plus_minus_changes(dataf = df,
                                     y = outcome,
                                     comps = comp.names,
                                     comps_fup = comp_fup,
                                     covars = covs,
                                     deltas = seq(xlim[1], xlim[2], by = 1)/(24*60),
                                     # balance = balance,
                                     comparisons = comparisons,
                                     alpha=0.05, verbose=FALSE)

  # Define reallocations for plots
  inc = increase
  if(length(inc) == 0) inc = comp[1]

  dec = decrease
  if(length(dec) == 0) dec = comp[-1]

  # Subset data to plot
  if(comparisons == "one-v-one"){
    data = plot_data[which(plot_data$`comp-` %in% dec &
                             plot_data$`comp+` == inc),]
    colnames(data)[which(colnames(data) == "comp-")] = "Replaced"
    # PLOT
    if(length(font) > 0) windowsFonts(Times=windowsFont(font))

    yourPlot = ggplot2::ggplot(data) +
      ggplot2::geom_hline(yintercept = 0, color = "black") +
      # geom_line(aes(delta, delta_pred, group = Replaced, color = Replaced), size = 2) +
      ggplot2::geom_line(ggplot2::aes(delta, delta_pred, group = Replaced), size = 2) +
      # Settings
      ggplot2::theme_bw()+
      ggplot2::labs(x=xlab,
           y=ylab) +
      ggplot2::scale_x_continuous(breaks = seq(xlim[1], xlim[2], by = xaxis.by)/1440,
                         labels = seq(xlim[1], xlim[2], by = xaxis.by)) +
      ggplot2::scale_y_continuous(limits=ylim) +
      # theme(text=element_text(family="Times", size = 12))
      ggplot2::theme(text=ggplot2::element_text(size = 12))

    # RIBBON?
    if(isTRUE(ribbon)){
      yourPlot = yourPlot +
        ggplot2::geom_ribbon(ggplot2::aes(x = delta, ymin = ci_lo, ymax = ci_up,
                        group = Replaced), alpha = 0.2)
    }
  } else if(comparisons == "prop-realloc"){
    data = plot_data[which(plot_data$`comp+` == inc),]

    # PLOT
    # windowsFonts(Times=windowsFont("Times New Roman"))

    yourPlot = ggplot2::ggplot(data) +
      ggplot2::geom_hline(yintercept = 0, color = "black") +
      ggplot2::geom_line(ggplot2::aes(delta, delta_pred), size = 2) +

      # Settings
      ggplot2::theme_bw()+
      ggplot2::labs(x=xlab, y=ylab) +
      ggplot2::scale_x_continuous(breaks = seq(xlim[1], xlim[2], by = xaxis.by)/1440,
                         labels = seq(xlim[1], xlim[2], by = xaxis.by)) +
      ggplot2::scale_y_continuous(limits=ylim) +
      # theme(text=element_text(family="Times", size = 12))
      ggplot2::theme(text=ggplot2::element_text(size = 12))

    # RIBBON?
    if(isTRUE(ribbon)){
      yourPlot = yourPlot +
        ggplot2::geom_ribbon(aes(x = delta, ymin = ci_lo, ymax = ci_up),
                    alpha = 0.2, colour= NA)
    }
  }

  return(yourPlot)
}
