#' reallocationPlot
#' @description Visualization of predictions from CoDA model
#'
#' @param data Data frame with the data
#' @param comp String with the name of the composition variables in dataf
#' @param comp_fup String with the name of the follow-up composition variables in dataf (optional)
#' @param comp.names Names of the composition variables to appear in the plot (it will use \code{comp} if not provided)
#' @param outcome String with the name of the outcome in dataf
#' @param covs String with the name of the covariates
#' @param comparisons Two choices ("one-v-one" or "prop-realloc")
#' @param increase What variable in the composition should increase in the visualization (replacement)
#' @param decrease What variable/s in the composition should decrease in the visualization (replaced)
#' @param xlab X axis label
#' @param ylab Y axis label
#' @param xlim Limits of the X axis (time reallocation limits)
#' @param ylim Limits for the Y axis (autogenerated if not provided)
#' @param xaxis.by X axis ticks at every \code{xaxis.by} minutes
#' @param ribbon Logical. Whether to plot confidence intervals of the predictions
#' @param font Font to use (default = "Times New Roman")
#' @param main Title of the plot
#' @param col Color for lines and confidence intervals
#' @param alpha Alpha for transparency in confidence intervals
#' @param ReallocationLimits limits for the reallocation time in minutes (vector of 2 numbers)
#' @param longAnalysis either prospective or change
#'
#' @details If follow-up composition is provided, it will run prospective and change models/visualizations
#' @return reallocation plot with predictions
#' @export
#'
reallocationPlot = function(data = c(), comp = c(),
                            comp_fup = NULL,
                            comp.names = c(),
                            outcome = c(), covs = c(),
                            comparisons=c("one-v-one","prop-realloc")[1],
                            # balance = NULL,
                            increase = c(), decrease = c(),
                            xlab = c(), ylab = c(),
                            xlim = c(), ylim = c(),
                            ReallocationLimits = c(-60, 60),
                            xaxis.by = 5,
                            ribbon = TRUE,
                            font = "Times New Roman",
                            main = NULL, col = "black",
                            alpha = 0.2,
                            longAnalysis = c("prospective", "change")[1]) {
  # define dataset
  df = data[, c(comp, outcome, covs)]
  if (!is.null(comp_fup)) df = data[,c(comp, comp_fup, outcome, covs)]
  
  # keep only complete.cases
  df = df[complete.cases(df),]

  if (length(comp.names) == length(comp)) {
    colnames(df)[1:length(comp)] = comp.names
    comp = comp.names
  } else {warning("composition names is of different length than the number of
                  elements in the composition. comp.names argument is not used.")}

  # Redefine comparisons if incompatible with increase/decrease
  if (comparisons == "prop-realloc" & length(decrease) > 0) {
    warning("Proportional reallocations and decrease arguments incompatible.\n comparisons now set to 'one-v-one'")
    comparisons = "one-v-one"
  }

  # get predictions.
  plot_data = myfunctions::get_plus_minus_changes(dataf = df,
                                     y = outcome,
                                     comps = comp.names,
                                     comps_fup = comp_fup,
                                     covars = covs,
                                     deltas = seq(ReallocationLimits[1], ReallocationLimits[2], by = 1)/1440,
                                     # balance = balance,
                                     comparisons = comparisons,
                                     longAnalysis = longAnalysis,
                                     alpha = 0.05, verbose = FALSE)

  # Define reallocations for plots
  inc = increase
  if (length(inc) == 0) inc = comp[1]
  if (length(inc) > 1) stop("The function can only handle increasing time in one component at a time. Increase argument should have lenght 1.")
  
  if (length(decrease) > 1 & comparisons == "one-v-one") {
    stop("At the moment the one-v-one plot can only handle one behavior to increase and one behavior to decrease. There are more than 1 behavior to decrease, please select only 1.")
  }
  dec = decrease
  if (length(dec) == 0) dec = comp[-1]
  
  # Subset data
  if (length(dec) == 1) {
    data = plot_data[which(plot_data$`comp-` %in% dec &
                             plot_data$`comp+` %in% inc),]
  } else if (length(dec) > 1) {
    data = plot_data[which(plot_data$`comp+` %in% inc),]
  }
  colnames(data)[which(colnames(data) == "comp-")] = "Replaced"
  
  # define xlab and ylab if it is not defined
  if (length(xlab) == 0) {
    xlab = paste0("\U2191", dec, " \U2194 ", "\U2191", inc, "\n(min/day)")
    if (length(dec) > 1) xlab = paste0("Min/day proportionally reallocated to ", inc)
  }
  
  # redefine xlim to multiples of 5
  xlim = floor(xlim/5) * 5
  
  # PLOT
  par(las = 1)
  plot(x = data$delta, y = data$delta_pred, type = "l",
       main = main, col = col, lwd = 3, 
       xlim = xlim/1440,
       ylim = ylim, xaxt = "n",
       ylab = ylab, xlab = xlab)
  abline(h = 0)
  axis(side = 1, at = seq(xlim[1], xlim[2], by = xaxis.by)/1440,
       labels = seq(xlim[1], xlim[2], by = xaxis.by))
  
  # ribbon 1
  if (ribbon) {
    polygon(x = c(data$delta, rev(data$delta)), y = c(data$ci_lo, rev(data$ci_up)),
            border = NA, col = add_alpha(col, alpha), fillOddEven = FALSE)
  }
}
